# Exploring data {#exploring-data}

This unit focuses on data visualization and data wrangling.
Specifically we cover fundamentals of data and data visualization, confounding variables, and Simpson's paradox as well as the concept of tidy data, data import, data cleaning, and data curation.
We end the unit with web scraping and introduce the idea of iteration in preparation for the next unit.
Also in this unit students are introduced to the toolkit: R, RStudio, R Markdown, Git, and GitHub.

## Visualising data

::: {.slide-deck}
**Unit 2 - Deck 1: Data and visualisation**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d01-data-viz/u2-d01-data-viz.html#1)
:::

::: {.video}
[Video](https://youtu.be/FddF4b_GuTI)
:::
:::

::: {.slide-deck}
**Unit 2 - Deck 2: Visualising data with ggplot2**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d02-ggplot2/u2-d02-ggplot2.html#1)
:::

::: {.video}
[Video](https://youtu.be/s2NF2J36ljE)
:::

::: {.reading}
R4DS :: [Chp 3 - Data visualization](https://r4ds.had.co.nz/data-visualisation.html)
:::
:::

::: {.slide-deck} **Unit 2 - Deck 3: Visualising numerical data**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d03-viz-num/u2-d03-viz-num.html#1)
:::

::: {.video}
[Video](https://youtu.be/waBabVTI8ec)
:::

::: {.reading}
IMS :: [Chp 4 - Exploring numerical data](https://openintro-ims.netlify.app/explore-numerical.html):::
:::

::: {.slide-deck}
**Unit 2 - Deck 4: Visualising categorical data**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d04-viz-cat/u2-d04-viz-cat.html#1)
:::

::: {.video}
[Video](https://youtu.be/21h3rEO8k2E)
:::

::: {.reading}
IMS :: [Chp 5 - Exploring categorical data](https://openintro-ims.netlify.app/explore-categorical.html)
:::
:::

## Wrangling and tidying data

::: {.slide-deck}
**Unit 2 - Deck 5: Tidy data**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d05-tidy-data/u2-d05-tidy-data.html#1)
:::

::: {.video}
[Video](https://youtu.be/Ux85eR3h9hw)
:::

::: {.reading}
JSS :: [Tidy data](https://www.jstatsoft.org/article/view/v059i10)
:::
:::

::: {.slide-deck}
**Unit 2 - Deck 6: Grammar of data wrangling**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d06-grammar-wrangle/u2-d06-grammar-wrangle.html#1)
:::

::: {.video}
[Video](https://youtu.be/ZCaYBES_VEk)
:::
:::

::: {.slide-deck}
**Unit 2 - Deck 7: Working with a single data frame**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d07-single-df/u2-d07-single-df.html#1)
:::

::: {.video}
[Video](https://youtu.be/0229Uq2hkJo)
:::

::: {.reading}
R4DS :: [Chp 5 - Data transformation](https://r4ds.had.co.nz/transform.html)
:::
:::

::: {.slide-deck}
**Unit 2 - Deck 8: Working with multiple data frames**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d08-multi-df/u2-d08-multi-df.html#1)
:::

::: {.video}
[Video](https://youtu.be/VdV5ABsaf5Y)
:::

::: {.reading}
R4DS :: [Chp 13 - Relational data](https://r4ds.had.co.nz/relational-data.html)
:::
:::

::: {.slide-deck}
**Unit 2 - Deck 9: Tidying data**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d09-tidying/u2-d09-tidying.html#1)
:::

::: {.video}
[Video](https://youtu.be/x3KM5uxaFdI)
:::

::: {.reading}
R4DS :: [Chp 12 - Tidy data](https://r4ds.had.co.nz/tidy-data.html)
:::
:::

## Importing and recoding data

::: {.slide-deck}
**Unit 2 - Deck 10: Data types**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d10-data-types/u2-d10-data-types.html#1)
:::

::: {.source}
[Source](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/slides/u2-d10-data-types)
:::

::: {.video}
[Video](https://youtu.be/WsxLbtWbEfc)
:::
:::

::: {.slide-deck}
**Unit 2 - Deck 11: Data classes**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d11-data-classes/u2-d11-data-classes.html#1)
:::

::: {.source}
[Source](https://github.com/rstudio-education/datascience-box/tree/master/course-materials/slides/u2-d11-data-classes)
:::

::: {.video}
[Video](https://youtu.be/dozvSVQcqqg)
:::

::: {.reading}
R4DS :: [Chp 15 - Factors](https://r4ds.had.co.nz/factors.html)
:::
:::

::: {.slide-deck}
**Unit 2 - Deck 12: Importing data**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d12-data-import/u2-d12-data-import.html#1)
:::

::: {.video}
[Video](https://youtu.be/tIMaRYiuEFA)
:::

::: {.reading}
R4DS :: [Chp 11 - Data import](https://r4ds.had.co.nz/data-import.html)
:::
:::

::: {.slide-deck}
**Unit 2 - Deck 13: Recoding data**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d13-data-recode/u2-d13-data-recode.html#1)
:::

::: {.video}
[Video](https://youtu.be/O8qxV3N4D5Q)
:::

::: {.reading}
R4DS :: [Sec 16.1 - 16.3 - Dates and times](https://r4ds.had.co.nz/dates-and-times.html)
:::
:::

## Communicating data science results effectively

::: {.slide-deck}
**Unit 2 - Deck 14: Tips for effective data visualization**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d14-effective-dataviz/u2-d14-effective-dataviz.html#1)
:::

::: {.video}
[Video](https://youtu.be/ZrifrBvFWgg)
:::

::: {.reading}
IMS :: [Chp 6 - Applications: Explore](https://openintro-ims.netlify.app/explore-applications.html)
:::
:::

::: {.slide-deck}
**Unit 2 - Deck 15: Scientific studies and confounding**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d15-studies-confounding/u2-d15-studies-confounding.html#1)
:::

::: {.video}
[Video](https://youtu.be/WnMzTBrZDcc)
:::

::: {.reading}
IMS :: [Chp 2 - Study design](https://openintro-ims.netlify.app/data-design.html)
:::
:::

::: {.slide-deck}
**Unit 2 - Deck 16: Simpson's paradox**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d16-simpsons-paradox/u2-d16-simpsons-paradox.html#1)
:::

::: {.video}
[Video](https://youtu.be/sdas62v0iJU)
:::
:::

::: {.slide-deck}
**Unit 2 - Deck 17: Doing data science**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d17-doing-data-science/u2-d17-doing-data-science.html#1)
:::

::: {.video}
[Video](https://youtu.be/b9lSW0kyqBg)
:::

::: {.reading}
R4DS :: [Chp 7 - Exploratory data analysis](https://r4ds.had.co.nz/exploratory-data-analysis.html)
:::
:::

## Web scraping and programming

::: {.slide-deck}
**Unit 2 - Deck 18: Web scraping**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d18-web-scrape/u2-d18-web-scrape.html#1)
:::

::: {.video}
[Video](https://youtu.be/99Hkmfb2i80)
:::
:::

::: {.slide-deck}
**Unit 2 - Deck 19: Scraping top 250 movies on IMDB**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d19-top-250-imdb/u2-d19-top-250-imdb.html#1)
:::

::: {.video}
[Video](https://youtu.be/YmKULNLsDsU)
:::
:::

::: {.slide-deck}
**Unit 2 - Deck 20: Web scraping considerations**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d20-considerations/u2-d20-considerations.html#1)
:::

::: {.video}
[Video](https://youtu.be/LONRJHMvSyU)
:::
:::

::: {.slide-deck}
**Unit 2 - Deck 21: Functions**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d21-functions/u2-d21-functions.html#1)
:::

::: {.video}
[Video](https://youtu.be/6KWlPhPMluE)
:::

::: {.reading}
R4DS :: [Chp 19 - Functions](https://r4ds.had.co.nz/functions.html)
:::
:::

::: {.slide-deck}
**Unit 2 - Deck 22: Iteration**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d22-iteration/u2-d22-iteration.html#1)
:::

::: {.video}
[Video](https://youtu.be/x3UMny1fQhc)
:::

::: {.reading}
R4DS :: [Chp 20 - Iteration](https://r4ds.had.co.nz/iteration.html)
:::
:::
