# Making rigorous conclusions {#making-rigorous-conclusions}

In this part we introduce modelling and statistical inference for making data-based conclusions.
We discuss building, interpreting, and selecting models, visualizing interaction effects, and prediction and model validation.
Statistical inference is introduced from a simulation based perspective, and the Central Limit Theorem is discussed very briefly to lay the foundation for future coursework in statistics.

## Modelling data

::: {.slide-deck}
**Unit 4 - Deck 1: The language of models**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u4-d01-language-of-models/u4-d01-language-of-models.html#1)
:::

::: {.video}
[Video](https://youtu.be/MWkkvDopBKc)
:::
:::

::: {.slide-deck}
**Unit 4 - Deck 2: Fitting and interpreting models**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u4-d02-fitting-interpreting-models/u4-d02-fitting-interpreting-models.html#1)
:::

::: {.video}
[Video](https://youtu.be/69U92Q3pwnA)
:::

::: {.reading}
IMS :: [Chp 7 - Linear regression with a single predictor](https://openintro-ims.netlify.app/model-slr.html)
:::
:::

::: {.slide-deck}
**Unit 4 - Deck 3: Modelling nonlinear relationships**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u4-d03-modeling-nonlinear-relationships/u4-d03-modeling-nonlinear-relationships.html#1)
:::

::: {.video}
[Video](https://youtu.be/j4MZ6ZdHnHg)
:::
:::

::: {.slide-deck}
**Unit 4 - Deck 4: Models with multiple predictors**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u4-d04-model-multiple-predictors/u4-d04-model-multiple-predictors.html#1)
:::

::: {.video}
[Video](https://youtu.be/mjkNabD4oi4)
:::

::: {.reading}
IMS :: [Chp 8 - Linear regression with multiple predictors](https://openintro-ims.netlify.app/model-mlr.html)
:::
:::

::: {.slide-deck}
**Unit 4 - Deck 5: More models with multiple predictors**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u4-d05-more-model-multiple-predictors/u4-d05-more-model-multiple-predictors.html#1)
:::

::: {.video}
[Video](https://youtu.be/nJAYRnLPb10)
:::
:::

## Classification and model building

::: {.slide-deck}
**Unit 4 - Deck 6: Logistic regression**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u4-d06-logistic-reg/u4-d06-logistic-reg.html#1)
:::

::: {.video}
[Video](https://youtu.be/AidXFYSYfJg)
:::

::: {.reading}
IMS :: [Chp 9 - Logistic regression](https://openintro-ims.netlify.app/model-logistic.html)
:::
:::

::: {.slide-deck}
**Unit 4 - Deck 7: Prediction and overfitting**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u4-d07-prediction-overfitting/u4-d07-prediction-overfitting.html#1)
:::

::: {.video}
[Video](https://youtu.be/Qd4lu_Lmwi0)
:::

::: {.reading}
tidymodels :: [Build a model](https://www.tidymodels.org/start/models/)
:::
:::

::: {.slide-deck}
**Unit 4 - Deck 8: Feature engineering**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u4-d08-feature-engineering/u4-d08-feature-engineering.html#1)
:::

::: {.video}
[Video](https://youtu.be/wZt9ab4jBZ4)
:::

::: {.reading}
tidymodels :: [Preprocess your data with recipes](https://www.tidymodels.org/start/recipes/)
:::
:::

## Model validation

::: {.slide-deck}
**Unit 4 - Deck 9: Cross validation**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u4-d09-cross-validation/u4-d09-cross-validation.html#1)
:::

::: {.video}
[Video](https://youtu.be/L1KfIISmUT4)
:::

::: {.reading}
tidymodels :: [Evaluate your model with resampling](https://www.tidymodels.org/start/resampling/)
:::
:::

## Uncertainty quantification

::: {.slide-deck}
**Unit 4 - Deck 10: Quantifying uncertainty**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u4-d10-quantify-uncertainty/u4-d10-quantify-uncertainty.html#1)
:::

::: {.video}
[Video](https://youtu.be/LYpKrtZmQtI)
:::
:::

::: {.slide-deck}
**Unit 4 - Deck 11: Bootstrapping**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u4-d11-bootstrap/u4-d11-bootstrap.html#1)
:::

::: {.video}
[Video](https://youtu.be/bdqpI3iVOso)
:::

::: {.reading}
IMS :: [Chp 12 - Confidence intervals with bootstrapping](https://openintro-ims.netlify.app/foundations-bootstrapping.html)
:::
:::

::: {.slide-deck}
**Unit 4 - Deck 12: Hypothesis testing**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u4-d12-hypothesis-testing/u4-d12-hypothesis-testing.html#1)
:::

::: {.reading}
[IMS :: Chp 11 - Hypothesis testing with randomization](https://openintro-ims.netlify.app/foundations-randomization.html)
:::
:::

::: {.slide-deck}
**Unit 4 - Deck 13: Inference overview**

::: {.slides}
[Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u4-d13-inference-overview/u4-d13-inference-overview.html#1)
:::
:::
