# Schedule

The list of topics is tentative and the pacing is subject to change depending on how much we cover each day.
We will aim to stick to the due dates outlined below.
If a deadline needs to change due to unforeseen circumstances, it will be push until a later date, never pulled up to an earlier date.

+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
| Week | Date        | Topic                                                                                                            | Readings                                                              | Due                                                                                                                                 |
+:====:+=============+==================================================================================================================+=======================================================================+=====================================================================================================================================+
| 1    | Wed, Aug 25 | [Welcome](https://vizdata-f21.github.io/slides/01-welcome/01-welcome.html#1)                                     |                                                                       |                                                                                                                                     |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
|      | Fri, Aug 27 | [Grammar of Graphics](https://vizdata-f21.github.io/slides/02-grammar-of-graphics/02-grammar-of-graphics.html#1) | [Wickham et al., Chp 13](https://ggplot2-book.org/mastery.html)       | Survey: [Getting to know you](https://sakai.duke.edu/samigo-app/servlet/Login?id=6fa7ebf3-01af-42a6-91ba-3e813d3901221629867759400) |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
| 2    | Mon, Aug 30 | Lab: Meet the toolkit\                                                                                           |                                                                       |                                                                                                                                     |
|      |             |                                                                                                                  |                                                                       |                                                                                                                                     |
|      |             | See repo titled [`exercise-01`](https://github.com/vizdata-f21) for instructions.[^schedule-1]                   |                                                                       |                                                                                                                                     |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
|      | Wed, Sep 1  | Looking at data                                                                                                  | [Healy, Chp 1](https://socviz.co/lookatdata.html#lookatdata)          | [RQ 1](https://minecr.shinyapps.io/vizdata-f21-rq-01/)[^schedule-2]                                                                 |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
|      | Fri, Sep 3  | Telling a story                                                                                                  | [Wilke, Chp 29](https://clauswilke.com/dataviz/telling-a-story.html)  |                                                                                                                                     |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
| 3    | Mon, Sep 6  | Work on HW 1                                                                                                     |                                                                       |                                                                                                                                     |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
|      | Wed, Sep 8  | Build a plot in layers                                                                                           | [Wickham et al., Chp 14](https://ggplot2-book.org/layers.html)        | HW 1[^schedule-3]                                                                                                                   |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
|      | Fri, Sep 10 | Scales and guides                                                                                                | [Wickham et al., Chp 15](https://ggplot2-book.org/scales-guides.html) |                                                                                                                                     |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
| 4    | Mon, Sep 13 | Work on Project 1                                                                                                |                                                                       |                                                                                                                                     |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
|      | Wed, Sep 15 | Coordinate systems                                                                                               | [Wickham et al., Chp 16](https://ggplot2-book.org/coord.html)         | RQ 2                                                                                                                                |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
|      | Fri, Sep 17 | Faceting and themes                                                                                              | [Wickham et al., Chp 17 - 18](https://ggplot2-book.org/facet.html)    | Project 1 proposal                                                                                                                  |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
| 5    | Mon, Sep 20 | Project 1 peer review                                                                                            |                                                                       |                                                                                                                                     |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
|      | Wed, Sep 22 | Guest lecture by Claus Wilke: Colors                                                                             | [Wilke, Chp 4](https://clauswilke.com/dataviz/color-basics.html)      | HW 2                                                                                                                                |
|      |             |                                                                                                                  |                                                                       |                                                                                                                                     |
|      |             |                                                                                                                  | [Wilke, Chp 19](https://clauswilke.com/dataviz/color-pitfalls.html)   |                                                                                                                                     |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
|      | Fri, Sep 24 | Axes, annotation, and compounding                                                                                |                                                                       |                                                                                                                                     |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
| 6    | Mon, Sep 27 | Work on Project 1                                                                                                |                                                                       |                                                                                                                                     |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
|      | Wed, Sep 29 | Presentation ready plots                                                                                         |                                                                       |                                                                                                                                     |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
|      | Fri, Oct 1  | Project 1 presentation                                                                                           |                                                                       | Project 1                                                                                                                           |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
| 7    | Mon, Oct 4  | *No lab: Fall break*                                                                                             |                                                                       |                                                                                                                                     |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
|      | Wed, Oct 6  | *LECTURE*                                                                                                        |                                                                       | RQ 3                                                                                                                                |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
|      | Fri, Oct 8  | *LECTURE*                                                                                                        |                                                                       |                                                                                                                                     |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
| 8    | Mon, Oct 11 | *LAB*                                                                                                            |                                                                       |                                                                                                                                     |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
|      | Wed, Oct 13 | *LECTURE*                                                                                                        |                                                                       | HW 3                                                                                                                                |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
|      | Fri, Oct 15 | *LECTURE*                                                                                                        |                                                                       |                                                                                                                                     |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
| 9    | Mon, Oct 18 | *LAB*                                                                                                            |                                                                       |                                                                                                                                     |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
|      | Wed, Oct 20 | *LECTURE*                                                                                                        |                                                                       | RQ 4                                                                                                                                |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
|      | Fri, Oct 22 | *LECTURE*                                                                                                        |                                                                       |                                                                                                                                     |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
| 10   | Mon, Oct 25 | *LAB*                                                                                                            |                                                                       |                                                                                                                                     |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
|      | Wed, Oct 27 | *LECTURE*                                                                                                        |                                                                       | HW 4                                                                                                                                |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
|      | Fri, Oct 29 | *LECTURE*                                                                                                        |                                                                       |                                                                                                                                     |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
| 11   | Mon, Nov 1  | Work on Project 2                                                                                                |                                                                       |                                                                                                                                     |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
|      | Wed, Nov 3  | *LECTURE*                                                                                                        |                                                                       | RQ 5                                                                                                                                |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
|      | Fri, Nov 5  | *LECTURE*                                                                                                        |                                                                       | Project 2 proposal                                                                                                                  |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
| 12   | Mon, Nov 8  | Project 2 peer review                                                                                            |                                                                       |                                                                                                                                     |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
|      | Wed, Nov 10 | *LECTURE*                                                                                                        |                                                                       | HW 5                                                                                                                                |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
|      | Fri, Nov 12 | *LECTURE*                                                                                                        |                                                                       |                                                                                                                                     |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
| 13   | Mon, Nov 15 | Work on Project 2                                                                                                |                                                                       | Project 2 re-proposal[^schedule-4]                                                                                                  |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
|      | Wed, Nov 17 | *LECTURE*                                                                                                        |                                                                       | RQ 6                                                                                                                                |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
|      | Fri, Nov 19 | *LECTURE*                                                                                                        |                                                                       |                                                                                                                                     |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
| 14   | Mon, Nov 22 | *LAB*                                                                                                            |                                                                       |                                                                                                                                     |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
|      | Wed, Nov 24 | *No class: Thanksgiving*                                                                                         |                                                                       | HW 6                                                                                                                                |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
|      | Fri, Nov 26 | *No class: Thanksgiving*                                                                                         |                                                                       |                                                                                                                                     |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
| 15   | Mon, Nov 29 | Work on Project 2                                                                                                |                                                                       |                                                                                                                                     |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
|      | Wed, Dec 1  | *LECTURE*                                                                                                        |                                                                       |                                                                                                                                     |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
|      | Fri, Dec 3  | Project 2 presentation                                                                                           |                                                                       | Project 2                                                                                                                           |
+------+-------------+------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+

[^schedule-1]: Actually, the repo will be titled `exercise-01-YOUR_GITHUB_NAME` -- each student gets their own private repo.

[^schedule-2]: RQ is short for *reading quiz*.
    Due by noon (class time) on Wed, Sep 1.
    Covers the following readings: [Wickham et al., Chp 13](https://ggplot2-book.org/mastery.html) and [Healy, Chp 1](https://socviz.co/lookatdata.html#lookatdata).

[^schedule-3]: HW is short for *homework*.

[^schedule-4]: Optional.
    This is an opportunity to improve your score on the Project 2 proposal by integrating feedback from the first round by this deadline.
    If you're happy with your Project 2 proposal score, you do not need to submit anything for this assignment.
